### ISSUE TITLE
permission denied after adding dependency to aspectd_impl

### ISSUE THREAD

**Issue by maheshmnj** [alibaba-flutter/aspectd#23]
when I am adding the dependency to aspectd_impl (pubspecyaml) as mentioned in step 2 and running flutter packages get I am getting permission denied cloning error

```
dependencies:
  flutter:
    sdk: flutter
  aspectd:
    git:
      url: git@github.com:alibaba-flutter/aspectd.git
      ref: master
  example:
    path: ../
```

```
[aspectd_impl] flutter packages get
Running "flutter pub get" in aspectd_impl...                    
Git error. Command: git clone --mirror git@github.com:alibaba-flutter/aspectd.git /home/al004/flutter_linux_v1.7.8+hotfix.4-stable/flutter/.pub-cache/git/cache/aspectd-13577356093be3047a2bed83d4a388403aa4c5c6

Cloning into bare repository '/home/al004/flutter_linux_v1.7.8+hotfix.4-stable/flutter/.pub-cache/git/cache/aspectd-13577356093be3047a2bed83d4a388403aa4c5c6'...
git@github.com: Permission denied (publickey).


fatal: Could not read from remote repository.



Please make sure you have the correct access rights
and the repository exists.
```
