### ISSUE TITLE
a package may not list itself as a dependency conflict

### ISSUE THREAD

**Issue by maheshmnj** [alibaba-flutter/aspectd#24]
I have a flutter project called ```testproject``` I have created a dart package names aspectd_impl inside my project and in the pubspec I have added the dependency  
```
dependencies:
  flutter:
    sdk: flutter
  aspectd:
    git:
      url: https://github.com/alibaba-flutter/aspectd.git
      ref: master
  testproject:
    path: ../
```

even if I make it to example it gives an error

```
dependencies:
  flutter:
    sdk: flutter
  aspectd:
    git:
      url: https://github.com/alibaba-flutter/aspectd.git
      ref: master
  example:
    path: ../

```

```
../pubspec.yaml: "name" field doesn't match expected name "example".

```
