### ISSUE TITLE
Permission denied - when changing pubspec.yaml in apectd_impl

### ISSUE THREAD

**Issue by shero1111** [alibaba-flutter/aspectd#87]
Hello,

I have following pubspec.yaml in aspectd_impl package:

```
dependencies:
  flutter:
    sdk: flutter
  aspectd:
    git:
      url: git@github.com:alibaba-flutter/aspectd.git
      ref: master
  aop_app:
    path: ../
```

**So when running Pub get... following error happens in log:**
```
Git error. Command: git clone --mirror git@github.com:alibaba-flutter/aspectd.git /Users/myName/.pub-cache/git/cache/aspectd-13577356093be3047a2bed83d4a388403aa4c5c6
stdout: 
stderr: Cloning into bare repository '/Users/myName/.pub-cache/git/cache/aspectd-13577356093be3047a2bed83d4a388403aa4c5c6'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
```

What to do so?
